### ISSUE TITLE
Bagaimana pendapatnya, lebih prefer belajar javascript atau python?

### ISSUE THREAD

**Issue by wachidmudi** [rizafahmi/ama#1]
Jadi setelah baca artikel ini https://hackernoon.com/could-pythons-popularity-outperform-javascript-in-the-next-five-years-abed4e307224, saya jadi mempertanyakan kembali tentang masa depan javascript.

Terimakasih, semoga formatnya bener!

**Comment by rizafahmi** [comment]
Halo mas @wachidmudi. Terimakasih sudah jadi penanya pertama :)

Untuk JavaScript atau Python, keduanya bahasa pemrograman yang bagus untuk mulai belajar pemrograman. Pilih aja salah satu jangan terlalu mengikuti tren. Artikel itu juga sebenarnya kan prediksi, judulnya aja pertanyaan bukan pernyataan :)

Jadi tergantung jalur yang dipilih juga. Misalnya mas @wachidmudi mau belajar web development, baik frontend dan backend sampai saat ini web masih dikuasai JavaScript. Satu-satunya yang jalan di browser masih JavaScript. Ditambah JavaScript juga sekarang sudah bisa buat backend bahkan mobile, iot dan lain sebagainya.
Tapi kalo mau fokus ke backend saja, atau bahkan nantinya bisa mengarah ke data engineering dan machine learning Python bisa menjadi pilihan.

Atau, kenapa tidak dua-duanya aja?! 👿 

Intinya, pilih aja salah satu, fokus belajar. Tutup mata terhadap tren dan perkembangan yang terjadi saat masa belajar. Ketika sudah merasa cukup kompeten, baru buka mata lagi lihat perkembangan dan tren, pilih bahasa atau platform lain dan belajar lagi, tutup mata lagi dan seterusnya :)

Semoga menjawab.

**Comment by wachidmudi** [comment]
Ok deh mas, terimakasih infonya. Jadi musti "Tutup mata terhadap tren dan perkembangan yang terjadi saat masa belajar." 😂👍
