### ISSUE TITLE
Framework / library apa untuk pre-render react app ke HTML (untuk case seperti Blog Post)

### ISSUE THREAD

**Issue by rizasatyabudhi** [rizafahmi/ama#2]
Hi mas, saat ini saya sedang membuat halaman article pada aplikasi saya menggunakan react. Data article nya berasal dari Backend REST API. Saya ingin membuat agar data article tersebut dapat di pre-render menjadi HTML sehingga dapat di crawl Google dan membuat SEO lebih baik. Saya sudah mencoba beberapa library seperti https://github.com/stereobooster/react-snap, tetapi jika ada data fetching dari API, data tersebut tidak di render di HTML. 

Kalau menggunakan Gatsby, tetap harus melakukan proses `build` agar data baru tersebut di render di HTML. Saya menghindari untuk melakukan `build` setiap article baru muncul. 

Saya juga sudah mencoba Next JS, tetapi sangat banyak dependency nya sehingga saya menghindari framework tersebut.

Apakah ada saran mas?
Terimakasih

**Comment by rizafahmi** [comment]
Hai @rizasatyabudhi. Wah, nama depan kita sama :D

Opsinya ada tiga: pakai nextjs (ngga mau kan), pake service seperti prerender.cloud, atau buat service sendiri untuk server-side rendering-nya React yang ujung-ujungnya create your own nextjs. Kenapa nextjs banyak dependencies karena server-side rendering memang ngga mudah dilakukan. Coba cek dependencies nextjs, dan di audit, kalo memang aman, harusnya ngga masalah dong?!

**Comment by rizasatyabudhi** [comment]
Hai mas salam kenal, iyaa nama depan kita sama 😂 , waktu itu saya attend di TIA PDC 2017 saat mas jadi speaker tentang PWA hehe

Siip mas, thank you sarannya. Sekarang saya lagi audit dependencies nya nextjs, kalau semua edge cases nya pass, saya akan rewrite ke next js.

Thank you sarannya mas!

**Comment by rizafahmi** [comment]
Ok siap @rizasatyabudhi. Next time ketemu offline kita ngobrol-ngobrol ya. Ini saya close ya. Sukses buat projectnya. Makasi pertanyaannya.
