### ISSUE TITLE
Apakah Javascript bisa menggantikan Python untuk AI Programming?

### ISSUE THREAD

**Issue by antonkristiono** [rizafahmi/ama#3]
Perkenalkan saya Anton Om, Saya Awalnya belajar Web programming dengan Python , namun menjadi Stuck di Javascript karena mengikuti perkembangan yang ada.... dan peluang perkerjaan juga di javascript yg lbh banyak..

Saat ini saya bekerja di start up di kota saya, yang awalnya saya mendaftar menjadi front end , sekarang di push menjadi fullstack ( karena beberapa service beckend beralih menggunakan python  ), beralih dari java ke python secara pelan2. karena kebutuhan perusahaan kedepan harus menerapkan ai ( meliputi machine learning dan deep learning tentunya).... dari awal saya memang tertarik dengan ai programming. Menjadi pertanyaan saya apakah kedepan Javascript bisa menggantikan kepopuleran Python untuk ai programming karena semakin kesini bannyak sekali library2 ai di npm,, seperti opencv.js tensorflow.js dan lain2nya?

**Comment by rizafahmi** [comment]
Halo @AntonKristiono kalau ditanya apakah JavaScript akan menggantikan Python untuk machine learning saya rasa tidak atau mungkin belum untuk jangka waktu yang lama, menurut saya. Coba perhatikan misalnya tensorflowjs, tetap membutuhkan bantuan server terutama untuk training model. Bisa sih training model di tensorflowjs, tapi biasanya yang dilakukan untuk training satu pengguna saja, sedangkan model utamanya tetap ditrain di sisi server. Jadi sebenarnya adanya library js hanya untuk meringankan kerja server, bukan menggantikan.

Saran dari saya daripada memusingkan belajar bahasa atau teknologi apa akan jauh lebih penting belajar konsep dasarnya. Toh tensorflow di c++, python atau js menggunakan konsep serupa. Dan ketika konsep dasarnya sudah dikuasai, pindah bahasa sudah bukan perkara besar lagi.

Dan tidak ada salahnya juga menguasai javascript dan python. Keduanya merupakan bahasa yang bagus dan saling melengkapi.

**Comment by antonkristiono** [comment]
terima kasih mas masukan-nya,,, siap laksanakan,, belum ada yang menggantikan ke elegan-nya ( kemudahan membaca ) syntax python juga mas
